# Generated by Django 3.0.8 on 2020-07-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200722_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='imageURL',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
