# Generated by Django 3.0.8 on 2020-07-25 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200725_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='current_bid',
            new_name='bid',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
