# Generated by Django 3.0.8 on 2020-07-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200725_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='updated_at',
        ),
    ]
